version: "3.7"
services:
  flask_app:
    build: 
      dockerfile: DockerFile
      context: app
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    depends_on:
      - redis
    
  worker:
    build:
      dockerfile: DockerFile
      context: worker
    user: nobody
    depends_on:
      - redis
      - flask_app

  redis:
    container_name: redis
    image: redis:5.0.5
    hostname: redis
    ports:
      - '6379:6379'
