FROM python:3.9.0

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

ADD . /app
WORKDIR /app

ENV FLASK_ENV=development
ENV FLASK_APP=__init__.py

CMD flask run --host=0.0.0.0
# ENV FLASK_APP=routes.py

# CMD [ "python", "-m", "flask", "run", "--host=0.0.0.0"]

# COPY . .

# EXPOSE 5000

# CMD [ "python", "routes.py" ]