FROM python:3.9.0

# layer caching for faster builds
COPY requirements.txt /
RUN pip install -r /requirements.txt

#COPY app.py /app.py
ADD . /worker
WORKDIR /worker

ENTRYPOINT celery -A tasks worker --loglevel=info -P gevent